module(
    name = "gloop",
    bazel_compatibility = [">=9.0.0"],
)

bazel_dep(name = "abseil-cpp", version = "20260107.1")
bazel_dep(name = "tcmalloc", version = "0.0.0-20250927-12f2552")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.16")

cc_configure = use_extension("@rules_cc//cc:extensions.bzl", "cc_configure_extension")
use_repo(cc_configure, "local_config_cc")

# Detect the distribution name and make it available to the build to enforce Debian-only support.
host_ext = use_extension("//gloop:distro_detector.bzl", "host_distro_detector_extension")
use_repo(host_ext, "host_distro")

# Dev dependencies, not needed for users of Gloop.

bazel_dep(name = "googletest", version = "1.17.0.bcr.2", dev_dependency = True)
bazel_dep(name = "google_benchmark", version = "1.9.5", dev_dependency = True)

# Override our visibility settings in Abseil with a patch.  Once Gloop is public and in BCR, we can
# upstream this patch into Abseil and declare a noop dependency there for enabling visibility.
# TODO: Make Gloop public
# TODO: Add Gloop to BCR
single_version_override(
    module_name = "abseil-cpp",
    patches = ["//gloop:abseil.patch"],
    version = "20260107.1",
)
