module(
    name = "gloop",
    bazel_compatibility = [">=8.0.0"],
)

bazel_dep(name = "abseil-cpp", version = "20260107.1")
bazel_dep(name = "protobuf", version = "33.5")
bazel_dep(name = "tcmalloc", version = "0.0.0-20250927-12f2552")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.16")
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "googletest", version = "1.17.0.bcr.2")
bazel_dep(name = "zlib", version = "1.3.2")

cc_configure = use_extension("@rules_cc//cc:extensions.bzl", "cc_configure_extension")
use_repo(cc_configure, "local_config_cc")

# Dev dependencies, not needed for users of Gloop.

bazel_dep(name = "re2", version = "2025-11-05.bcr.1", dev_dependency = True)
bazel_dep(name = "google_benchmark", version = "1.9.5", dev_dependency = True)

# Override our visibility settings in with patches.  Once Gloop is public and in BCR, we can
# upstream these changes and declare a noop dependency in these repos for enabling visibility.
# TODO: Make Gloop public
# TODO: Add Gloop to BCR
git_override(
    module_name = "abseil-cpp",
    commit = "7dac70835cfe89563a8be0ee832a2b035b96b669",
    patches = ["//gloop:abseil.patch"],
    remote = "https://github.com/abseil/abseil-cpp",
)

git_override(
    module_name = "tcmalloc",
    commit = "29bae22bff6cd2adcb32972f1cb4928f34dfa213",
    patches = ["//gloop:tcmalloc.patch"],
    remote = "https://github.com/google/tcmalloc",
)
