// Copyright 2026 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Removing the following header is prohibited as it can introduce undefined
// behavior.
// clang-format off
#include "gloop/enforce_gloop_support.h"
// clang-format on

// Anti-codex is the opposite of codex -- it takes
// ascii data, formatted in a variety of ways, and lets you create all
// sorts of binary data structures.  This can be used as a way to convert
// from human-editable datafiles to something machines can use efficiently.
//
// Usually, we accept input via a FileLineReader, which means we
// expect one piece of data per line, blank lines are ignored, and
// lines can start with a # to indicate a comment.

// TODO: add lots more converters: SortedMap(?), etc.

#include <string.h>

#include <cstdint>
#include <fstream>
#include <ios>
#include <iterator>
#include <memory>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include "absl/flags/flag.h"
#include "absl/log/check.h"
#include "absl/log/log.h"
#include "absl/status/status.h"
#include "absl/strings/numbers.h"
#include "absl/strings/str_split.h"
#include "absl/strings/string_view.h"
#include "gloop/base/init_google.h"
#include "gloop/strings/escaping.h"
#include "gloop/strings/serialize.h"
#include "gloop/util/gtl/sparse_hash_map.h"
#include "gloop/util/gtl/sparse_hash_set.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/descriptor.pb.h"
#include "google/protobuf/descriptor_database.h"
#include "google/protobuf/dynamic_message.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
#include "google/protobuf/text_format.h"
#include "google/protobuf/util/json_util.h"

// "string" is passed as an argument to macros in this program and is then both
// stringified to compare with command-line flags, and used as an actual type.
// This using-declaration allows string to mean std::string.
using std::string;

namespace proto2 {
class Descriptor;
}  // namespace proto2

ABSL_FLAG(std::string, output, "",
          "What kind of output you want: "
          "sparse_hash_set, "
          "sparse_hash_map, "
          "protobuf, "
          "json (<link>), "
          "(more TODO)");

ABSL_FLAG(bool, useglobaldb, false,
          "Deprecated.  Please use --use_global_db instead.");
ABSL_FLAG(std::string, protoname, "",
          "The name of the protocol message to output value");
ABSL_FLAG(std::string, key_protoname, "",
          "The name of the protocol message to output key");

ABSL_FLAG(std::string, input_filename, "/dev/stdin",
          "Where the input comes from");
ABSL_FLAG(std::string, output_filename, "/dev/stdout",
          "Where to write the output to");

ABSL_FLAG(std::string, key_value_separator, "",
          "What character(s) you use to separate key from value in "
          "files with key/value maps (sparse_hash_map"
          ") (input is '<key><sep><value>\n...')");

// TODO: keys can't be float/double because we don't know how to hash them
ABSL_FLAG(std::string, key_type, "string",
          "The type of the hash-map key.  We support builtin types: "
          "string, char, "
          "int16, uint16, int32, uint32, int64, uint64.");
ABSL_FLAG(int32_t, key_base, 10,
          "What base to interpret the input keys (8, 10, or 16)");

ABSL_FLAG(std::string, value_type, "string",
          "The type of the hash-map value.  We support builtin types: "
          "string, char, float, double, "
          "int16, uint16, int32, uint32, int64, uint64.");

ABSL_FLAG(int32_t, value_base, 10,
          "What base to interpret the input values (8, 10, or 16)");
ABSL_FLAG(int32_t, line_buffer_size, 64 * 1024,
          "Buffer size to use when reading input");

ABSL_FLAG(
    std::string, proto_descriptor_set, "",
    "Proto descriptors, including extensions and transitive dependencies, "
    "as a comma-separated list of binary FileDescriptorSet files, "
    "e.g. generated by transitive_descriptor_set. If this flag is set, "
    "--protofiles and --proto_paths will be ignored.");
namespace {

// ----------------------------------------------------------------------
// Convert()
// Write()
// WriteAs()
//    This templatized function wraps the stringstream we use to do
//    the actual conversion from a string to a simple type.  It
//    RETURNS true if we converted the entire input, false else,
//    and puts the converted value in ToType.
// ----------------------------------------------------------------------

template <typename ToType>
bool Convert(absl::string_view input, ToType* output, int base) {
  std::istringstream input_stream((std::string(input)));

  if (base == 8) {
    input_stream >> std::oct >> *output;
  } else if (base == 16) {
    input_stream >> std::hex >> *output;
  } else {
    input_stream >> *output;  // every other value taken as 10
  }
  if (input_stream.bad() || input_stream.fail()) {
    LOG(WARNING) << "Can't convert '" << input << "' to proper output type";
    return false;  // make sure we converted ok
  }

  // Try to read 1 extra character to make sure there's nothing left
  char c;
  input_stream >> c;
  if (!input_stream.eof()) {
    LOG(WARNING) << "'" << input << "' has extra chars at the end (" << c
                 << ")";
    return false;
  }

  return true;
}

// We specialize strings: no need to convert in that case!
template <>
bool Convert(absl::string_view input, std::string* output, int base) {
  output->assign(input);  // could be made more efficient, but whatever
  return true;
}

// ----------------------------------------------------------------------
// AbstractEncoder
//    This is an interface for encoding keys.
// ----------------------------------------------------------------------
class AbstractEncoder {
 public:
  virtual ~AbstractEncoder() {}

  // Encodes the key from the input file returns the result.
  // Returns false if input cannot be parsed.
  virtual bool Encode(const std::string& input, std::string* result) const = 0;
};

// AbstractEncoder used for all built-in types.
template <typename IntType>
class IntegerEncoder : public AbstractEncoder {
 public:
  virtual bool Encode(const std::string& input, std::string* result) const {
    IntType value;
    if (!Convert(input, &value, absl::GetFlag(FLAGS_key_base))) {
      return false;
    }
    *result = strings::EncodePOD(value);
    return true;
  }
};

// AbstractEncoder used for 'fp64'.
class Fp64Encoder : public AbstractEncoder {
 public:
  virtual bool Encode(const std::string& input, std::string* result) const {
    uint64_t value;
    if (!absl::SimpleAtoi(input, &value)) {
      return false;
    }
    *result = strings::Uint64ToKey(value);
    return true;
  }
};

// AbstractEncoder used for 'doublekey'.
class DoubleKeyEncoder : public AbstractEncoder {
 public:
  virtual bool Encode(const std::string& input, std::string* result) const {
    double value;
    if (!absl::SimpleAtod(input, &value)) {
      return false;
    }
    strings::KeyFromDouble(value, result);
    return true;
  }
};

// AbstractEncoder used for 'string'.
class StringEncoder : public AbstractEncoder {
 public:
  virtual bool Encode(const std::string& input, std::string* result) const {
    result->assign(input);
    return true;
  }
};

// AbstractEncoder used for protocol buffer encoding
class ProtoEncoder : public AbstractEncoder {
 public:
  ProtoEncoder(const std::string& pb_name,
               const google::protobuf::DescriptorPool& pool) {
    CHECK(!pb_name.empty());
    desc_ = pool.FindMessageTypeByName(pb_name);
    CHECK(desc_ != nullptr) << "Failed to find proto type [" << pb_name << "]";
  }
  virtual bool Encode(const std::string& input, std::string* result) const {
    google::protobuf::DynamicMessageFactory dynamic_message_factory;
    google::protobuf::Message* instance =
        dynamic_message_factory.GetPrototype(desc_)->New();
    CHECK(google::protobuf::TextFormat::ParseFromString(input, instance))
        << "Failed to parse ASCII [" << input << "]";

    std::string local_result;
    {
      // Use a nested block to guarantee triggering coded_stream's destructor
      // before `result` is used. Due to copy elision, this code works without
      // the nested block, but small, innocent looking changes can break it.
      // See <link> for more details.
      google::protobuf::io::StringOutputStream string_stream(&local_result);
      google::protobuf::io::CodedOutputStream coded_stream(&string_stream);
      coded_stream.SetSerializationDeterministic(true);
      CHECK(instance->SerializeToCodedStream(&coded_stream))
          << "Failed to serialize message to coded stream";
    }
    *result = std::move(local_result);

    delete instance;
    return true;
  }

 protected:
  const google::protobuf::Descriptor* desc_;
};

// AbstractEncoder used for string unscaping
class UnescapeEncoder : public AbstractEncoder {
 public:
  virtual bool Encode(const std::string& input, std::string* result) const {
    strings::UnescapeCEscapeString(input, result);
    return true;
  }
};

// Given a ProtocolDB, reads an ASCII representation of protocol
// buffer proto_name from file input_filename and writes the binary
// or jspb representation to a file called output_filename.  If unsucessful,
// this function logs a warning and returns.
void ReadAsciiProtoBuf(const google::protobuf::DescriptorPool& pool,
                       const std::string& proto_name,
                       const std::string& input_filename,
                       absl::string_view output_filename,
                       absl::string_view output_format) {
  std::ifstream file(input_filename, std::ios::in | std::ios::binary);
  if (!file) {
    LOG(FATAL) << "Failed to open input file [" << input_filename << "]";
  }
  std::string ascii_message((std::istreambuf_iterator<char>(file)),
                            std::istreambuf_iterator<char>());

  if (ascii_message.empty()) {
    LOG(WARNING) << "Input was empty; proceeding anyway";
  }

  const google::protobuf::Descriptor* descriptor =
      pool.FindMessageTypeByName(proto_name);
  CHECK(descriptor) << "Failed to find proto type [" << proto_name << "]";

  google::protobuf::DynamicMessageFactory message_factory;
  const google::protobuf::Message* prototype =
      message_factory.GetPrototype(descriptor);
  CHECK(prototype) << "Couldn't get prototype message.";

  std::unique_ptr<google::protobuf::Message> message(prototype->New());
  google::protobuf::TextFormat::Parser parser;
  google::protobuf::io::ArrayInputStream asciipb_istream(ascii_message.data(),
                                                         ascii_message.size());
  CHECK(parser.Parse(&asciipb_istream, message.get()))
      << "Failed to parse text format proto buffer from input file "
      << input_filename;

  if (output_format == "json") {
    std::string json_data;
    google::protobuf::util::JsonPrintOptions options;
    CHECK_OK(google::protobuf::util::MessageToJsonString(*message, &json_data,
                                                         options));
    std::ofstream file(output_filename.data(),
                       std::ios::out | std::ios::binary);
    if (!file) {
      LOG(FATAL) << "Failed to open output file [" << output_filename << "]";
    }
    file << json_data;
    CHECK(file.good());
  }
}

bool MatchesKeyType(absl::string_view key_type) {
  std::string flag = absl::GetFlag(FLAGS_key_type);
  // cl/362169587 accidentally changed the meaning of key_type to include
  // _t on numeric types, check for that for backward compatibility.
  if (flag.length() > 2 && flag.substr(flag.length() - 2, 2) == "_t") {
    flag = flag.substr(0, flag.length() - 2);
  }
  return flag == key_type;
}

template <typename T>
AbstractEncoder* CreateEncoder(absl::string_view key_type) {
  return MatchesKeyType(key_type) ? new IntegerEncoder<T> : nullptr;
}

};  // namespace

// ----------------------------------------------------------------------
// main()
//    This is long mostly because we have lots of options.
// ----------------------------------------------------------------------

int main(int argc, char** argv) {
  InitGoogle(argv[0], &argc, &argv, true);

  if (absl::GetFlag(FLAGS_output).empty())
    LOG(FATAL) << "Must specify what kind of conversion you want via --output";
  CHECK(!absl::GetFlag(FLAGS_useglobaldb))
      << "Please use --use_global_db instead of --useglobaldb";

  google::protobuf::DescriptorPoolDatabase generated_db(
      *google::protobuf::DescriptorPool::generated_pool());
  google::protobuf::SimpleDescriptorDatabase descriptor_set_db;

  std::vector<google::protobuf::DescriptorDatabase*> descriptor_dbs;

  descriptor_dbs.push_back(&generated_db);

  // Now build a descriptor pool from either the parsed+generated protos,
  // or from the binary descriptor sets.
  google::protobuf::MergedDescriptorDatabase merged_descriptor_db(
      descriptor_dbs);
  google::protobuf::DescriptorPool merged_db(&merged_descriptor_db);

  LOG(INFO) << "Reading input from " << absl::GetFlag(FLAGS_input_filename);
  if (absl::GetFlag(FLAGS_output) == "protobuf" ||
      absl::GetFlag(FLAGS_output) == "json") {
    ::ReadAsciiProtoBuf(merged_db, absl::GetFlag(FLAGS_protoname),
                        absl::GetFlag(FLAGS_input_filename),
                        absl::GetFlag(FLAGS_output_filename),
                        absl::GetFlag(FLAGS_output));
  } else {
    LOG(FATAL) << "Unknown output conversion requested: "
               << absl::GetFlag(FLAGS_output);
  }

  LOG(INFO) << "DONE";
  return 0;
}
