// Copyright 2026 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Removing the following header is prohibited as it can introduce undefined
// behavior.
// clang-format off
#include "gloop/enforce_gloop_support.h"
// clang-format on

#include "gloop/util/status/status_macros.h"

#include <cerrno>
#include <string>

#include "absl/status/status.h"
#include "absl/status/status_macros.h"
#include "absl/status/statusor.h"
#include "gloop/util/status/posixerrorspace.h"
#include "gloop/util/status/status.h"
#include "gtest/gtest.h"

namespace {

TEST(AssignOrReturn, PreservesExplicitlySetCanonicalCode) {
  // Set up a status with an explicitly set canonical code (i.e. one that is not
  // generated by the error space).
  absl::Status error = util::PosixErrorToStatus(ENOSYS, "enosys");
  util::SetCanonicalCode(absl::StatusCode::kPermissionDenied, &error);

  // Obtain the error via ASSIGN_OR_RETURN, exercising the various code paths
  // that add context.
  const absl::Status transformed = [error]() -> absl::Status {
    ASSIGN_OR_RETURN(int dummy, absl::StatusOr<int>(error),
                     ((_ << "foo").SetAppend() << "bar").SetPrepend() << "baz");

    // Silence errors about an unused value.
    static_cast<void>(dummy);
    return absl::OkStatus();
  }();

  // The canonical code should have been preserved.
  EXPECT_EQ(absl::StatusCode::kPermissionDenied, transformed.code());
}

}  // namespace
