package(
    default_applicable_licenses = ["//third_party/gloop:license"],
)

# TODO: Remove this placeholder once there are a non-zero number of targets in this package.
#       This test_suite rule only serves to prevent TAP errors resulting from references to this
#       package in blueprints that resolve to zero rules.
test_suite(
    name = "placeholder",
    tags = ["-flaky"],
)
