name: Tests

on:
  # continuous
  schedule:
    # Run every hour
    - cron: "0 * * * *"

  # postsubmit
  push:
    branches:
      - main

  # presubmit
  pull_request:
    branches:
      - main

  # manual
  workflow_dispatch:

permissions:
  contents: read

# Avoid running twice at the same time over the same changes.
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ contains(fromJSON('["pull_request", "workflow_dispatch", "schedule"]'), github.event_name) }}

jobs:
  linux:
    # TODO(b/482506448) Private repos have lower disk space and can't handle the large abseil image.
    runs-on: ubuntu-latest-large
    name: Linux
    container:
      image: gcr.io/google.com/absl-177019/linux_hybrid-latest@sha256:9a5b056cd4fa4ff783e7ced7a660d21269dc74e8726c67bd7cce8b9e9da28c30
      # Our images happen to be public today, but use our service account's credentials anyway in
      # case we decide to lock down access.
      credentials:
        username: _json_key
        password: ${{ secrets.GAR_SERVICE_ACCOUNT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@083175551ceeceebc757ebee2127fde78840ca77 # 0.18.0
        with:
          bazelisk-cache: true
          cache-save: true
          external-cache: true
          repository-cache: |
            - MODULE.bazel
          google-credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazelrc: common --remote_cache=https://storage.googleapis.com/gloop-bazel-remote-cache

      - name: Run tests
        run: bazel test ...

  all-blocking-tests:
    name: All Blocking Tests
    needs: [linux]
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        run: "${{ !contains(join(needs.*.result, ' '), 'failure') && !contains(join(needs.*.result, ' '), 'cancelled') }}"
    # This workflow must run even if one or more of the dependent workflows
    # failed.
    if: always()
